services:
  backend:
    build: ./backend
    volumes:
      - /home/darkangel/ai-light-song-v2/data/fixtures:/app/fixtures:ro
    ports:
      - "5141:5141"

  frontend:
    build: ./frontend
    ports:
      - "5140:5140"
    depends_on:
      - backend
