services:
  backend:
    build: ./backend
    volumes:
      - ./data/fixtures:/app/fixtures:ro
      - ./backend/data:/app/data
    ports:
      - "5141:5141"

  frontend:
    build: ./frontend
    ports:
      - "5140:5140"
    depends_on:
      - backend
